version: '3.8'

services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=${DB_DATABASE}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_USER=${DB_USERNAME}'
    ports:
      - '3307:3306'
    networks:
      backend_net:
        ipv4_address: 172.20.0.5

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    networks:
      backend_net:
        ipv4_address: 172.20.0.6

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - java_app1
      - java_app2
      - java_app3
    networks:
      backend_net:
        ipv4_address: 172.20.0.14

  java_app1:
    image: 'openjdk:17-jdk-slim'
    container_name: java_app1
    ports:
      - '8081:8080'
    volumes:
      - './target/backend-atividades-0.0.1-SNAPSHOT.jar:/app.jar'
    entrypoint: ["java", "-jar", "/app.jar"]
    depends_on:
      - mysql
      - redis
    networks:
      backend_net:
        ipv4_address: 172.20.0.7

  java_app2:
    image: 'openjdk:17-jdk-slim'
    container_name: java_app2
    ports:
      - '8082:8080'
    volumes:
      - './target/backend-atividades-0.0.1-SNAPSHOT.jar:/app.jar'
    entrypoint: ["java", "-jar", "/app.jar"]
    depends_on:
      - mysql
      - redis
    networks:
      backend_net:
        ipv4_address: 172.20.0.8

  java_app3:
    image: 'openjdk:17-jdk-slim'
    container_name: java_app3
    ports:
      - '8083:8080'
    volumes:
      - './target/backend-atividades-0.0.1-SNAPSHOT.jar:/app.jar'
    entrypoint: ["java", "-jar", "/app.jar"]
    depends_on:
      - mysql
      - redis
    networks:
      backend_net:
        ipv4_address: 172.20.0.9

networks:
  backend_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
