version: '3.8'

services:
  db:
    image: postgres:13
    container_name: local-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=avadbdev
      - POSTGRES_DB=avadb_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
